### PR TITLE
ESPN and Yahoo Support

### PR DESCRIPTION
**Pull request by mikemountain**
This **SHOULD** bring in ESPN and Yahoo support for the board, along with some solid QOL/code improvements fixes I hope.

I've swapped to using python3, and there are some dependency changes due to that, so I'd probably recommend a clean install. 

I would absolutely love it if people could try this out and let me know if they find any errors or issues. I can't 100% guarantee the ESPN/Yahoo stuff will work right out of the gate either, but I will do my absolute best to ensure they're functional during the first Sunday of the season.

### CODE REVIEW

**Comment by mikemountain** [comment]
this will also close #7 and #20

**Comment by willsbeard** [comment]
Thanks Mike! I'll give it a go.

**Comment by morpherios** [comment]
Does it still take time for what's merged into master to go live? Attempted
to do the update to 1.0.0 last night and didn't seem to get any of the new
files.

Backed up the install and ran fresh and seemed to pull the old version.

**Comment by ethanschned** [comment]
Is there anyway you could add support for NFL fantasy football?

**Comment by mikemountain** [comment]
@ethanschned I've opened #38 to take a look at this - I will see what I can do over the next few days before week 2 starts (but ESPN/Yahoo support will take precedence if there are bugs)

**Comment by ethanschned** [comment]
Yeah, this would be cool to get more sites involved. I will definitely try to get one for my house

**Comment by morpherios** [comment]
Tried an upgrade and a fresh install. Same error on each.

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from data.data_test import DataTest
  File "/home/pi/fantasy-football-scoreboard/data/data_test.py", line 1, in
<module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone

**Comment by morpherios** [comment]
Sorry brother, away on vacation at the moment. Not even sure if I'm on
master or not to be honest. Won't have access to anything at home til the
weekend.

**Pull request merged**
