### PR TITLE
Yahoo improvements

### PR DESCRIPTION
**Pull request by jeremywww**
-Update Yahoo API to endpoint that respects the current week
-Properly download Yahoo team logos

### CODE REVIEW

**Comment by mikemountain** [comment]
Wow dude, thanks for this! This is awesome. I don't have great access to a Yahoo league so it was tough to get it all set up, really appreciate this!

**Comment by jeremywww** [comment]
No problem at all. Thanks for this awesome project!

**Comment by willsbeard** [comment]
Pulled down the new version to test. I think in 'yahoo_api_parser.py' it's missing team_id in the def init

**Comment by jeremywww** [comment]
Fixed in #29 ... how embarrassing. Thanks @willsbeard

**Pull request merged**
